GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/parts
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "solutionsContext": {
	"pixelgradelt-retailer/first-solution": {
	  "timestamp": 101
	},
	"pixelgradelt-retailer/fourth-solution": {
	  "timestamp": 102
	},
	"pixelgradelt-retailer/second-solution": {
	  "timestamp": 103
	},
	"pixelgradelt-retailer/third-solution": {
	  "timestamp": 104
	}
  }
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/instructions_to_update
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "composer": {
	"name": "pixelgradelt\/my-site",
	"type": "project",
	"license": "MIT",
	"description": "A Pixelgrade LT WordPress site.",
	"homepage": "https:\/\/local.local",
	"time": "2021-07-06T11:01:05+00:00",
	"authors": [
	  {
		"name": "Vlad Olaru",
		"email": "vlad@pixelgrade.com",
		"homepage": "https:\/\/thinkwritecode.com",
		"role": "Development, infrastructure, and product development"
	  }
	],
	"keywords": [],
	"support": {
	  "issues": "https:\/\/pixelgradelt.com",
	  "forum": "https:\/\/pixelgradelt.com"
	},
	"repositories": [
	  {
		"type": "composer",
		"url": "https:\/\/lt-records.local\/ltpackagist\/",
		"options": {
		  "ssl": {
			"verify_peer": false
		  }
		}
	  },
	  {
		"type": "composer",
		"url": "https:\/\/repo.packagist.org"
	  }
	],
	"require": {
	  "ext-json": "*",
	  "oscarotero\/env": "^2.1",
	  "php": ">=7.1",
	  "pixelgradelt-records\/part_another-test": "*, >=3.0.0",
	  "pixelgradelt-records\/part_spanky": "1.0.0",
	  "pixelgradelt-records\/part_test-test": "*, ^4.0",
	  "pixelgradelt-records\/part_yet-another": "*",
	  "roots\/bedrock-autoloader": "^1.0",
	  "roots\/wordpress": "*",
	  "roots\/wp-config": "1.0.0",
	  "roots\/wp-password-bcrypt": "1.0.0",
	  "vlucas\/phpdotenv": "^5.3"
	},
	"require-dev": {
	  "roave\/security-advisories": "dev-latest",
	  "squizlabs\/php_codesniffer": "^3.5.8"
	},
	"config": {
	  "optimize-autoloader": false,
	  "preferred-install": "dev"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "installer-paths": {
		"web\/app\/mu-plugins\/{$name}\/": [
		  "type:wordpress-muplugin"
		],
		"web\/app\/plugins\/{$name}\/": [
		  "type:wordpress-plugin"
		],
		"web\/app\/themes\/{$name}\/": [
		  "type:wordpress-theme"
		]
	  },
	  "lt-required-packages": {
		"pixelgradelt-records\/part_yet-another": {
		  "name": "pixelgradelt-records\/part_yet-another",
		  "version": "*",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/first-solution",
			  "requiredVersion": "*"
			}
		  ]
		},
		"pixelgradelt-records\/part_another-test": {
		  "name": "pixelgradelt-records\/part_another-test",
		  "version": "*, >=3.0.0",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pixelgradelt-retailer\/second-solution",
			  "requiredVersion": ">=3.0.0"
			}
		  ]
		},
		"pixelgradelt-records\/part_spanky": {
		  "name": "pixelgradelt-records\/part_spanky",
		  "version": "1.0.0",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/fourth-solution",
			  "requiredVersion": "1.0.0"
			}
		  ]
		},
		"pixelgradelt-records\/part_test-test": {
		  "name": "pixelgradelt-records\/part_test-test",
		  "version": "*, ^4.0",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pixelgradelt-retailer\/second-solution",
			  "requiredVersion": "^4.0"
			}
		  ]
		}
	  },
	  "lt-composition": "def50200f830e9646a8dc04858de8a9f6048a09ecab3134798ae88d94e57757e15569c75b8f7e5152bcf7c7b40f06d3c3176ab7a42aadeeac31447de35ca1f53ec576d386c45fd2524611d79bcdde353fa365d4223a67818f3cd9bfcd8810ea227ffdb3b1b806101e2fd805843bbccccf078b8142b656b4c4e30a392814a5763c6d168e60ccc256b68416d2ed31b7164e240607ce24e166eb667f80d051ef7e8983a",
	  "lt-version": "1.1.0",
	  "something": "yet",
	  "wordpress-install-dir": "web\/wp",
	  "lt-fingerprint": "39272ca959a46c699c52b1d062c50e1a"
	},
	"scripts": {
	  "post-root-package-install": [
		"php -r \"copy('.env.example', '.env');\""
	  ],
	  "test": [
		"phpcs"
	  ],
	  "test2": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/check_ltdetails
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "ltdetails": "def50200f830e9646a8dc04858de8a9f6048a09ecab3134798ae88d94e57757e15569c75b8f7e5152bcf7c7b40f06d3c3176ab7a42aadeeac31447de35ca1f53ec576d386c45fd2524611d79bcdde353fa365d4223a67818f3cd9bfcd8810ea227ffdb3b1b806101e2fd805843bbccccf078b8142b656b4c4e30a392814a5763c6d168e60ccc256b68416d2ed31b7164e240607ce24e166eb667f80d051ef7e8983a"
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/encrypt_ltdetails
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "userid": 1,
  "compositionid": "lwqGArXg",
  "extra": {
	"user-email": "test@test.com"
  }
}

###
