GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/parts
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json

###

GET https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/solutions/processed
Authorization: Basic Fry4YDsVZGs7UDvtLrHcR8fjEgdL8iG0 pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "solutionsContext": {
	"pixelgradelt-retailer/first-solution": {
	  "timestamp": 101
	},
	"pixelgradelt-retailer/fourth-solution": {
	  "timestamp": 102
	},
	"pixelgradelt-retailer/second-solution": {
	  "timestamp": 103
	},
	"pixelgradelt-retailer/third-solution": {
	  "timestamp": 104
	}
  }
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/details_to_update
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "composer": {
	"name": "pixelgradelt\/my-site",
	"type": "project",
	"license": "MIT",
	"description": "A Pixelgrade LT WordPress site.",
	"homepage": "https:\/\/local.local",
	"time": "2021-06-18T10:46:35+00:00",
	"authors": [
	  {
		"name": "Vlad Olaru",
		"email": "vlad@pixelgrade.com",
		"homepage": "https:\/\/thinkwritecode.com",
		"role": "Development, infrastructure, and product development"
	  }
	],
	"keywords": [],
	"support": {
	  "issues": "https:\/\/pixelgradelt.com",
	  "forum": "https:\/\/pixelgradelt.com"
	},
	"repositories": [
	  {
		"type": "composer",
		"url": "https:\/\/lt-records.local\/ltpackagist\/",
		"options": {
		  "ssl": {
			"verify_peer": false
		  }
		}
	  },
	  {
		"type": "composer",
		"url": "https:\/\/repo.packagist.org"
	  }
	],
	"require": {
	  "pixelgradelt-records\/part_another-test": "*, >=3.0.0",
	  "pixelgradelt-records\/part_test-test": "*, ^4.0",
	  "pixelgradelt-records\/part_yet-another": "*"
	},
	"require-dev": {},
	"config": {
	  "optimize-autoloader": true,
	  "preferred-install": "dist"
	},
	"minimum-stability": "stable",
	"prefer-stable": false,
	"extra": {
	  "installer-paths": {
		"web\/app\/mu-plugins\/{$name}\/": [
		  "type:wordpress-muplugin"
		],
		"web\/app\/plugins\/{$name}\/": [
		  "type:wordpress-plugin"
		],
		"web\/app\/themes\/{$name}\/": [
		  "type:wordpress-theme"
		]
	  },
	  "lt-required-packages": {
		"pixelgradelt-records\/part_yet-another": {
		  "name": "pixelgradelt-records\/part_yet-another",
		  "version": "*",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/first-solution",
			  "requiredVersion": "*"
			}
		  ]
		},
		"pixelgradelt-records\/part_another-test": {
		  "name": "pixelgradelt-records\/part_another-test",
		  "version": "*, >=3.0.0",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pixelgradelt-retailer\/second-solution",
			  "requiredVersion": ">=3.0.0"
			}
		  ]
		},
		"pixelgradelt-records\/part_test-test": {
		  "name": "pixelgradelt-records\/part_test-test",
		  "version": "*, ^4.0",
		  "requiredBy": [
			{
			  "name": "pixelgradelt-retailer\/fourth-solution",
			  "requiredVersion": "*"
			},
			{
			  "name": "pixelgradelt-retailer\/second-solution",
			  "requiredVersion": "^4.0"
			}
		  ]
		}
	  },
	  "lt-user": "def502008fcbc51955416f332382a99a0c6f21bbe3581542522a97a7e2794adf85bb9b573b8f0de2a2cc58958657036f0a07bd6657484bc63924222a43fe5bf6dc94696b97a6c1ea3a5d36378a78ca6a285fe21884202cad5129994e697b6a7e3ce901c61e42a42b1c6350e46099d4c0ce48624097a4e0ab92b16610fcd0112bab0c848b79e9b752d1349673585c52651d91162acadcd78f2df7d07c1e",
	  "wordpress-install-dir": "web\/wp",
	  "lt-fingerprint": "44e4291a4eb8be042e08da3fb6f96ce4"
	},
	"scripts": {
	  "post-root-package-install": [
		"php -r \"copy('.env.example', '.env');\""
	  ],
	  "test": [
		"phpcs"
	  ]
	}
  }
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/check_user_details
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "user": "def502008b590b343fbac515087976bfdab17466b1b9ac2be8dd7f257cfd8c0edbbe67378a2fdba577d914443b1e01cf9a622ccf00c5eb5e31ee6e0f7e30df66a2498a36f2da649aaf712b25fac0cca1b61cb39eae3404784a946acccbbb5c4232daa4e4802995e17dca0446f73d022950f1dd6a691f5a295c88b7434dbbb109073643696d6192ffca05c6bd84fb2edbeb89f66f49171cead428a153d3"
}

###

POST https://lt-retailer.local/wp-json/pixelgradelt_retailer/v1/compositions/encrypt_user_details
Authorization: Basic whtg94kNGV20FuOy7yTbqAi198hBMjyz pixelgradelt_retailer
Accept: application/json
Content-Type: application/json

{
  "userid": 1,
  "compositionid": "lwqGArXg",
  "extra": {
	"email": "test@test.com"
  }
}

###
